version: "3.8"
services:
  mongodb:
    image: "mongo:4.4.1"
    ports:
    - "27017:27017"
  morningfm:
    build: 
      context: .
      dockerfile: ./MorningFM/Dockerfile
    ports:
      - "5000:80"
    depends_on:
        - mongodb
    environment: 
        - ASPNETCORE_ENVIRONMENT=development