version: "3.8"
services:
  morningfm:
    build: 
      context: .
      dockerfile: ./MorningFM/Dockerfile
    ports:
      - "8080:80"
  mongodb:
    image: "mongo:4.4.1"
    ports:
    - "27017:27017"